### ISSUE TITLE
'mainAmogOS-KDE v. 1.0 Alpha (link)' leads to 'AmogOS-x86_64 .ova' and not a AmogOS-KDE rar!

### ISSUE THREAD

**Issue by programing-monkey** [Amog-OS/AmogOS-KDE#2]
[mainAmogOS-KDE v. 1.0 Alpha (link)](https://github.com/Amog-OS/AmogOS-KDE/blob/main/AmogOS-KDE%20v.%201.0%20Alpha%20(link)) currently leads [this file on mega](https://mega.nz/file/GLoBCCTK#_1I4UbgvbiCOC3pFM1X0FlYPPrnuUdB1LMd629QPRZA) which is called "AmogOS-x86_64 .ova" as seen here 
![image](https://user-images.githubusercontent.com/36543893/144356763-9f3881e5-950c-4e7f-bfe4-916c1d09be62.png)

**Comment by MarcelDev** [comment]
It's meant for Virtual Machines
